name: "@logging"
description: ""
namespace: "Logging\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
  - "Logger"

# Class members to exclude, they override "export".
force-internal:

# Dependencies: other modulites, global classes, defines, etc.
require:
  - "@db"

# Granting partial access to internal symbols, "as an exception".
allow-internal-access:
