name: "@messi/folders"
description: ""
namespace: "Messinger\\Folders\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
  - "FolderActions"

# Class members to exclude, they override "export".
force-internal:

# Dependencies: other modulites, global classes, defines, etc.
require:
  - "\\Users\\User"
  - "\\Users\\UserSettings"

# Granting partial access to internal symbols, "as an exception".
allow-internal-access:
