name: "@db"
description: ""
namespace: "DB\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
  - "DbConnection"
  - "StorableObject"

# Class members to exclude, they override "export".
force-internal:

# Dependencies: other modulites, global classes, defines, etc.
require:

# Granting partial access to internal symbols, "as an exception".
allow-internal-access:
  "@logging":
    - "MysqlAdaptor::insertToLogsTable()"
