name: "@messi/channels"
description: ""
namespace: "Messinger\\Channels\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
  - "ChannelActions"

# Class members to exclude, they override "export".
force-internal:

# Dependencies: other modulites, global classes, defines, etc.
require:
  - "@messi/kernel"

# Granting partial access to internal symbols, "as an exception".
allow-internal-access:
